# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configdialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(317, 313)
        ConfigDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ConfigDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RB_local = QtWidgets.QRadioButton(ConfigDialog)
        self.RB_local.setChecked(True)
        self.RB_local.setObjectName("RB_local")
        self.buttonGroup = QtWidgets.QButtonGroup(ConfigDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.RB_local)
        self.horizontalLayout.addWidget(self.RB_local)
        self.RB_pi = QtWidgets.QRadioButton(ConfigDialog)
        self.RB_pi.setObjectName("RB_pi")
        self.buttonGroup.addButton(self.RB_pi)
        self.horizontalLayout.addWidget(self.RB_pi)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(ConfigDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ConfigDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(ConfigDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(ConfigDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.LE_ip = QtWidgets.QLineEdit(ConfigDialog)
        self.LE_ip.setObjectName("LE_ip")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LE_ip)
        self.LE_name = QtWidgets.QLineEdit(ConfigDialog)
        self.LE_name.setObjectName("LE_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LE_name)
        self.LE_password = QtWidgets.QLineEdit(ConfigDialog)
        self.LE_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LE_password.setObjectName("LE_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LE_password)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(ConfigDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RB_demo = QtWidgets.QRadioButton(ConfigDialog)
        self.RB_demo.setChecked(True)
        self.RB_demo.setObjectName("RB_demo")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(ConfigDialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.RB_demo)
        self.verticalLayout.addWidget(self.RB_demo)
        self.RB_own = QtWidgets.QRadioButton(ConfigDialog)
        self.RB_own.setObjectName("RB_own")
        self.buttonGroup_2.addButton(self.RB_own)
        self.verticalLayout.addWidget(self.RB_own)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PB_change = QtWidgets.QPushButton(ConfigDialog)
        self.PB_change.setObjectName("PB_change")
        self.horizontalLayout_2.addWidget(self.PB_change)
        self.PB_cancel = QtWidgets.QPushButton(ConfigDialog)
        self.PB_cancel.setObjectName("PB_cancel")
        self.horizontalLayout_2.addWidget(self.PB_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ConfigDialog)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Select configuration"))
        self.RB_local.setText(_translate("ConfigDialog", "Local"))
        self.RB_pi.setText(_translate("ConfigDialog", "Raspberry"))
        self.label_4.setText(_translate("ConfigDialog", "Data for the connection to the Pi"))
        self.label.setText(_translate("ConfigDialog", "IP:"))
        self.label_2.setText(_translate("ConfigDialog", "Name:"))
        self.label_3.setText(_translate("ConfigDialog", "Password:"))
        self.label_5.setText(_translate("ConfigDialog", "Option for the Database"))
        self.RB_demo.setText(_translate("ConfigDialog", "Demo Database"))
        self.RB_own.setText(_translate("ConfigDialog", "Own Database"))
        self.PB_change.setText(_translate("ConfigDialog", "Change"))
        self.PB_cancel.setText(_translate("ConfigDialog", "Cancel"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfigDialog = QtWidgets.QDialog()
    ui = Ui_ConfigDialog()
    ui.setupUi(ConfigDialog)
    ConfigDialog.show()
    sys.exit(app.exec_())
