# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desctopdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DesctopMainWindow(object):
    def setupUi(self, DesctopMainWindow):
        DesctopMainWindow.setObjectName("DesctopMainWindow")
        DesctopMainWindow.resize(492, 405)
        DesctopMainWindow.setStyleSheet("#L_debts{\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(DesctopMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.CB_modify = QtWidgets.QComboBox(self.centralwidget)
        self.CB_modify.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.CB_modify.setObjectName("CB_modify")
        self.verticalLayout_5.addWidget(self.CB_modify)
        self.LE_modify_firstname = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_modify_firstname.setMinimumSize(QtCore.QSize(50, 20))
        self.LE_modify_firstname.setMaximumSize(QtCore.QSize(16777215, 100))
        self.LE_modify_firstname.setObjectName("LE_modify_firstname")
        self.verticalLayout_5.addWidget(self.LE_modify_firstname)
        self.LE_modify_lastname = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_modify_lastname.setMinimumSize(QtCore.QSize(50, 20))
        self.LE_modify_lastname.setMaximumSize(QtCore.QSize(16777215, 100))
        self.LE_modify_lastname.setObjectName("LE_modify_lastname")
        self.verticalLayout_5.addWidget(self.LE_modify_lastname)
        self.CHB_active = QtWidgets.QCheckBox(self.centralwidget)
        self.CHB_active.setObjectName("CHB_active")
        self.verticalLayout_5.addWidget(self.CHB_active)
        self.PB_change = QtWidgets.QPushButton(self.centralwidget)
        self.PB_change.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_change.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_change.setFont(font)
        self.PB_change.setObjectName("PB_change")
        self.verticalLayout_5.addWidget(self.PB_change)
        self.gridLayout.addLayout(self.verticalLayout_5, 5, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.LE_firstname = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_firstname.setMinimumSize(QtCore.QSize(50, 20))
        self.LE_firstname.setMaximumSize(QtCore.QSize(16777215, 100))
        self.LE_firstname.setObjectName("LE_firstname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LE_firstname)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.LE_lastname = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_lastname.setMinimumSize(QtCore.QSize(50, 20))
        self.LE_lastname.setMaximumSize(QtCore.QSize(16777215, 100))
        self.LE_lastname.setObjectName("LE_lastname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LE_lastname)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.PB_new = QtWidgets.QPushButton(self.centralwidget)
        self.PB_new.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_new.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_new.setFont(font)
        self.PB_new.setObjectName("PB_new")
        self.verticalLayout_2.addWidget(self.PB_new)
        self.gridLayout.addLayout(self.verticalLayout_2, 4, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.CB_active = QtWidgets.QComboBox(self.centralwidget)
        self.CB_active.setMaximumSize(QtCore.QSize(16777215, 50))
        self.CB_active.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.CB_active.setObjectName("CB_active")
        self.verticalLayout_3.addWidget(self.CB_active)
        self.L_debts = QtWidgets.QLabel(self.centralwidget)
        self.L_debts.setMinimumSize(QtCore.QSize(0, 0))
        self.L_debts.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.L_debts.setFont(font)
        self.L_debts.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.L_debts.setObjectName("L_debts")
        self.verticalLayout_3.addWidget(self.L_debts)
        self.PB_default = QtWidgets.QPushButton(self.centralwidget)
        self.PB_default.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_default.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_default.setFont(font)
        self.PB_default.setObjectName("PB_default")
        self.verticalLayout_3.addWidget(self.PB_default)
        self.gridLayout.addLayout(self.verticalLayout_3, 4, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.LE_payment = QtWidgets.QLineEdit(self.centralwidget)
        self.LE_payment.setMinimumSize(QtCore.QSize(50, 20))
        self.LE_payment.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LE_payment.setFont(font)
        self.LE_payment.setObjectName("LE_payment")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LE_payment)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.PB_pay = QtWidgets.QPushButton(self.centralwidget)
        self.PB_pay.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_pay.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_pay.setFont(font)
        self.PB_pay.setObjectName("PB_pay")
        self.verticalLayout_4.addWidget(self.PB_pay)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_add_coffee = QtWidgets.QPushButton(self.centralwidget)
        self.PB_add_coffee.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_add_coffee.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_add_coffee.setFont(font)
        self.PB_add_coffee.setObjectName("PB_add_coffee")
        self.horizontalLayout.addWidget(self.PB_add_coffee)
        self.PB_undo = QtWidgets.QPushButton(self.centralwidget)
        self.PB_undo.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_undo.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_undo.setFont(font)
        self.PB_undo.setObjectName("PB_undo")
        self.horizontalLayout.addWidget(self.PB_undo)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.PB_plot = QtWidgets.QPushButton(self.centralwidget)
        self.PB_plot.setMinimumSize(QtCore.QSize(0, 30))
        self.PB_plot.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_plot.setFont(font)
        self.PB_plot.setObjectName("PB_plot")
        self.verticalLayout_4.addWidget(self.PB_plot)
        self.gridLayout.addLayout(self.verticalLayout_4, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        DesctopMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DesctopMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        DesctopMainWindow.setMenuBar(self.menubar)
        self.actionTodo = QtWidgets.QAction(DesctopMainWindow)
        self.actionTodo.setObjectName("actionTodo")
        self.actionAbout = QtWidgets.QAction(DesctopMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(DesctopMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCofigure_con = QtWidgets.QAction(DesctopMainWindow)
        self.actionCofigure_con.setObjectName("actionCofigure_con")
        self.menuHelp.addAction(self.actionTodo)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionExit)
        self.menuConfig.addAction(self.actionCofigure_con)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())

        self.retranslateUi(DesctopMainWindow)
        QtCore.QMetaObject.connectSlotsByName(DesctopMainWindow)

    def retranslateUi(self, DesctopMainWindow):
        _translate = QtCore.QCoreApplication.translate
        DesctopMainWindow.setWindowTitle(_translate("DesctopMainWindow", "Coffeetracker Desctop App"))
        self.label_7.setText(_translate("DesctopMainWindow", "Master: Modify User"))
        self.CHB_active.setText(_translate("DesctopMainWindow", "active"))
        self.PB_change.setText(_translate("DesctopMainWindow", "Change properties"))
        self.label_4.setText(_translate("DesctopMainWindow", "Add new User"))
        self.label_2.setText(_translate("DesctopMainWindow", "First Name:"))
        self.label_3.setText(_translate("DesctopMainWindow", "Last Name:"))
        self.PB_new.setText(_translate("DesctopMainWindow", "Enter into DB"))
        self.label.setText(_translate("DesctopMainWindow", "Select existing User"))
        self.L_debts.setText(_translate("DesctopMainWindow", "Balance:"))
        self.PB_default.setText(_translate("DesctopMainWindow", "Save as default"))
        self.label_8.setText(_translate("DesctopMainWindow", "Payment, Coffee and Plots"))
        self.label_6.setText(_translate("DesctopMainWindow", "Amount to Pay:"))
        self.PB_pay.setText(_translate("DesctopMainWindow", "Pay my debts!"))
        self.PB_add_coffee.setText(_translate("DesctopMainWindow", "Add Coffee"))
        self.PB_undo.setText(_translate("DesctopMainWindow", "Undo Add"))
        self.PB_plot.setText(_translate("DesctopMainWindow", "Plot Leaderboard"))
        self.label_5.setText(_translate("DesctopMainWindow", "<html><head/><body><p align=\"center\">Add coffee, pay debts or just</p><p align=\"center\">plot stuff for fun.</p></body></html>"))
        self.menuHelp.setTitle(_translate("DesctopMainWindow", "Help"))
        self.menuConfig.setTitle(_translate("DesctopMainWindow", "Config"))
        self.actionTodo.setText(_translate("DesctopMainWindow", "What to do?"))
        self.actionTodo.setStatusTip(_translate("DesctopMainWindow", "More information on how to use this app"))
        self.actionTodo.setShortcut(_translate("DesctopMainWindow", "Ctrl+H"))
        self.actionAbout.setText(_translate("DesctopMainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("DesctopMainWindow", "Information about this awesome app"))
        self.actionAbout.setShortcut(_translate("DesctopMainWindow", "Ctrl+I"))
        self.actionExit.setText(_translate("DesctopMainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("DesctopMainWindow", "Ctrl+X"))
        self.actionCofigure_con.setText(_translate("DesctopMainWindow", "Cofigure Database Connection"))
        self.actionCofigure_con.setStatusTip(_translate("DesctopMainWindow", "Set up the connection to the database"))
        self.actionCofigure_con.setShortcut(_translate("DesctopMainWindow", "Ctrl+D, Ctrl+B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DesctopMainWindow = QtWidgets.QMainWindow()
    ui = Ui_DesctopMainWindow()
    ui.setupUi(DesctopMainWindow)
    DesctopMainWindow.show()
    sys.exit(app.exec_())

